export type PersonalityProfile = {
  type: string;
  name: string;
  emoji: string;
  theme: string;
  summary: string;
  strengths: string[];
  growthAreas: string[];
  careers: string[];
  communication: string;
  workStyle: string;
  relationships: string;
  quote: string;
};

const profiles: PersonalityProfile[] = [
  { type:"INTJ",name:"Architect",emoji:"♟️",theme:"violet",summary:"Strategic, independent, and driven to improve complex systems.",strengths:["Strategic thinking","Independence","High standards","Long-term planning"],growthAreas:["Can seem overly critical","May overlook emotions","Can over-plan"],careers:["Software architect","Data scientist","Engineer","Researcher"],communication:"Direct, precise, and idea-focused.",workStyle:"Prefers autonomy, difficult problems, and clear competence.",relationships:"Values depth, loyalty, and intellectual compatibility.",quote:"Turn insight into a system that works." },
  { type:"INTP",name:"Logician",emoji:"🧠",theme:"violet",summary:"Curious, analytical, and energized by theories and possibilities.",strengths:["Analysis","Original ideas","Open-mindedness","Problem solving"],growthAreas:["Can procrastinate","May overthink","Can miss practical details"],careers:["Software engineer","Research scientist","Analyst","Inventor"],communication:"Exploratory, logical, and comfortable challenging assumptions.",workStyle:"Thrives with freedom to investigate and build elegant solutions.",relationships:"Connects through ideas, honesty, and shared curiosity.",quote:"Every assumption is an invitation to investigate." },
  { type:"ENTJ",name:"Commander",emoji:"🏆",theme:"violet",summary:"Decisive, ambitious, and skilled at organizing people around goals.",strengths:["Leadership","Efficiency","Confidence","Strategic execution"],growthAreas:["Can be impatient","May sound blunt","Can prioritize results over feelings"],careers:["Product leader","Entrepreneur","Consultant","Engineering manager"],communication:"Confident, direct, and outcome-oriented.",workStyle:"Likes ownership, measurable progress, and ambitious challenges.",relationships:"Shows care through commitment, protection, and problem solving.",quote:"A clear direction turns energy into progress." },
  { type:"ENTP",name:"Debater",emoji:"💡",theme:"violet",summary:"Inventive, energetic, and naturally drawn to new ideas and debate.",strengths:["Innovation","Quick thinking","Adaptability","Persuasion"],growthAreas:["Can lose interest","May debate too much","Can neglect follow-through"],careers:["Founder","Product manager","Creative technologist","Consultant"],communication:"Playful, challenging, and possibility-driven.",workStyle:"Enjoys experimentation, variety, and solving unusual problems.",relationships:"Brings humor, novelty, and lively conversation.",quote:"The best idea may be hiding behind the next question." },
  { type:"INFJ",name:"Advocate",emoji:"🔮",theme:"green",summary:"Insightful, principled, and motivated by meaningful improvement.",strengths:["Empathy","Vision","Creativity","Purpose"],growthAreas:["Can absorb stress","May be perfectionistic","Can avoid asking for help"],careers:["UX researcher","Counselor","Writer","Mission-driven engineer"],communication:"Thoughtful, warm, and focused on meaning.",workStyle:"Prefers purposeful work, depth, and collaborative trust.",relationships:"Seeks sincerity, emotional safety, and lasting connection.",quote:"Quiet insight can create lasting change." },
  { type:"INFP",name:"Mediator",emoji:"🌿",theme:"green",summary:"Imaginative, empathetic, and guided by deeply held personal values.",strengths:["Creativity","Empathy","Curiosity","Loyalty"],growthAreas:["Can overthink","May avoid conflict","Can be sensitive to criticism"],careers:["Software engineer","UX designer","Writer","Counselor"],communication:"Gentle, expressive, and values-centered.",workStyle:"Does best with autonomy, purpose, and room for creativity.",relationships:"Values authenticity, emotional depth, and mutual growth.",quote:"Your values can become something useful and beautiful." },
  { type:"ENFJ",name:"Protagonist",emoji:"🌟",theme:"green",summary:"Warm, organized, and skilled at helping people grow together.",strengths:["Encouragement","Leadership","Communication","Reliability"],growthAreas:["Can overextend","May seek approval","Can take criticism personally"],careers:["Team lead","Teacher","People operations","Product manager"],communication:"Expressive, supportive, and audience-aware.",workStyle:"Thrives in collaborative environments with visible human impact.",relationships:"Invests deeply and actively supports others' goals.",quote:"People grow faster when someone believes in them." },
  { type:"ENFP",name:"Campaigner",emoji:"🔥",theme:"green",summary:"Enthusiastic, imaginative, and inspired by people and possibility.",strengths:["Energy","Creativity","Connection","Adaptability"],growthAreas:["Can become distracted","May overcommit","Can struggle with routine"],careers:["Developer advocate","Designer","Entrepreneur","Marketing strategist"],communication:"Animated, encouraging, and idea-rich.",workStyle:"Likes variety, collaboration, and freedom to explore.",relationships:"Brings openness, enthusiasm, and emotional generosity.",quote:"Possibility becomes real when enthusiasm meets action." },
  { type:"ISTJ",name:"Logistician",emoji:"📘",theme:"blue",summary:"Dependable, practical, and committed to accuracy and responsibility.",strengths:["Reliability","Organization","Focus","Integrity"],growthAreas:["Can resist change","May be too rigid","Can carry too much alone"],careers:["Backend engineer","Auditor","Systems analyst","Operations manager"],communication:"Clear, factual, and careful.",workStyle:"Prefers stable expectations, ownership, and measurable quality.",relationships:"Shows loyalty through consistency and dependable action.",quote:"Trust is built through what you do repeatedly." },
  { type:"ISFJ",name:"Defender",emoji:"🛡️",theme:"blue",summary:"Caring, observant, and committed to supporting people in practical ways.",strengths:["Supportiveness","Attention to detail","Patience","Loyalty"],growthAreas:["Can neglect own needs","May avoid change","Can dislike conflict"],careers:["Healthcare technologist","QA engineer","Educator","Project coordinator"],communication:"Patient, considerate, and detail-aware.",workStyle:"Excels in supportive teams with clear responsibilities.",relationships:"Expresses care through attention, service, and consistency.",quote:"Small acts of care create strong systems of trust." },
  { type:"ESTJ",name:"Executive",emoji:"📊",theme:"blue",summary:"Organized, decisive, and focused on turning plans into dependable results.",strengths:["Execution","Structure","Responsibility","Leadership"],growthAreas:["Can be inflexible","May sound controlling","Can underestimate nuance"],careers:["Engineering manager","Operations lead","Business analyst","Project manager"],communication:"Direct, structured, and action-oriented.",workStyle:"Likes accountability, clear standards, and visible progress.",relationships:"Provides stability, commitment, and practical support.",quote:"A good plan matters when it becomes consistent action." },
  { type:"ESFJ",name:"Consul",emoji:"🤝",theme:"blue",summary:"Sociable, attentive, and motivated to create harmony and belonging.",strengths:["Cooperation","Practical care","Communication","Dependability"],growthAreas:["Can seek approval","May avoid hard disagreement","Can take rejection personally"],careers:["Customer success","Program manager","Recruiter","Community lead"],communication:"Friendly, responsive, and relationship-centered.",workStyle:"Thrives in connected teams with clear appreciation and impact.",relationships:"Creates warmth through attention, inclusion, and reliability.",quote:"Belonging grows when people feel seen." },
  { type:"ISTP",name:"Virtuoso",emoji:"🛠️",theme:"orange",summary:"Independent, calm, and skilled at understanding how things work.",strengths:["Practical problem solving","Adaptability","Composure","Technical skill"],growthAreas:["Can be private","May avoid long-term planning","Can take unnecessary risks"],careers:["Systems engineer","Security engineer","Mechanic","Robotics developer"],communication:"Concise, factual, and action-focused.",workStyle:"Prefers hands-on challenges, independence, and immediate feedback.",relationships:"Shows care through practical help and shared experiences.",quote:"Understand the mechanism, then improve it." },
  { type:"ISFP",name:"Adventurer",emoji:"🎨",theme:"orange",summary:"Sensitive, flexible, and quietly expressive through actions and aesthetics.",strengths:["Empathy","Adaptability","Observation","Creativity"],growthAreas:["Can avoid planning","May be overly private","Can struggle with criticism"],careers:["Frontend developer","Designer","Photographer","Healthcare professional"],communication:"Kind, personal, and non-confrontational.",workStyle:"Likes flexible environments where craft and human impact matter.",relationships:"Brings gentleness, acceptance, and present-moment care.",quote:"Authenticity is a form of quiet creativity." },
  { type:"ESTP",name:"Entrepreneur",emoji:"🚀",theme:"orange",summary:"Bold, practical, and energized by action, people, and fast decisions.",strengths:["Resourcefulness","Confidence","Observation","Action"],growthAreas:["Can be impulsive","May dislike routine","Can miss long-term consequences"],careers:["Sales engineer","Founder","Emergency responder","Product specialist"],communication:"Fast, candid, and engaging.",workStyle:"Thrives in dynamic environments with immediate challenges.",relationships:"Brings excitement, directness, and spontaneous support.",quote:"Momentum often begins with one bold experiment." },
  { type:"ESFP",name:"Entertainer",emoji:"🎉",theme:"orange",summary:"Warm, spontaneous, and energized by people and shared experiences.",strengths:["Optimism","Social awareness","Adaptability","Practical creativity"],growthAreas:["Can avoid difficult planning","May be distractible","Can take criticism personally"],careers:["Event producer","Customer experience","Designer","Content creator"],communication:"Expressive, warm, and engaging.",workStyle:"Likes people-centered work, variety, and visible results.",relationships:"Creates joy through presence, generosity, and shared experience.",quote:"Joy becomes meaningful when it is shared." },
];

export const personalityProfiles = Object.fromEntries(profiles.map((profile) => [profile.type, profile])) as Record<string, PersonalityProfile>;
export const personalityList = profiles;
